# Site settings
title: Chaitanya Bapat
email: chai.bapat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A full-stack developer, passionate and curious to learn new technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ChaiBapchya.github.io" # the base hostname & protocol for your site
twitter_username: ChaiBapchya
github_username:  ChaiBapchya

# Build settings
markdown: kramdown
